In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.formula.api as smf
pd.set_option('display.max_column',None)
from sklearn.linear_model import LinearRegression
from scipy.stats import f_oneway 
from statsmodels.stats.outliers_influence import variance_inflation_factor
import scipy.stats as stats

In [2]:
df = pd.read_csv("I:\\ML\\Class project EDA - h1n1\\h1n1_vaccine_prediction.csv")

In [3]:
df.head()

unique_id  h1n1_worry  h1n1_awareness  antiviral_medication  \
0          0         1.0             0.0                   0.0   
1          1         3.0             2.0                   0.0   
2          2         1.0             1.0                   0.0   
3          3         1.0             1.0                   0.0   
4          4         2.0             1.0                   0.0   

   contact_avoidance  bought_face_mask  wash_hands_frequently  \
0                0.0               0.0                    0.0   
1                1.0               0.0                    1.0   
2                1.0               0.0                    0.0   
3                1.0               0.0                    1.0   
4                1.0               0.0                    1.0   

   avoid_large_gatherings  reduced_outside_home_cont  avoid_touch_face  \
0                     0.0                        1.0               1.0   
1                     0.0                        1.0               1.0   
2                     0.0                        0.0               0.0   
3                     1.0                        0.0               0.0   
4                     1.0                        0.0               1.0   

   dr_recc_h1n1_vacc  dr_recc_seasonal_vacc  chronic_medic_condition  \
0                0.0                    0.0                      0.0   
1                0.0                    0.0                      0.0   
2                NaN                    NaN                      1.0   
3                0.0                    1.0                      1.0   
4                0.0                    0.0                      0.0   

   cont_child_undr_6_mnths  is_health_worker  has_health_insur  \
0                      0.0               0.0               1.0   
1                      0.0               0.0               1.0   
2                      0.0               0.0               NaN   
3                      0.0               0.0               NaN   
4                      0.0               0.0               NaN   

   is_h1n1_vacc_effective  is_h1n1_risky  sick_from_h1n1_vacc  \
0                     3.0            1.0                  2.0   
1                     5.0            4.0                  4.0   
2                     3.0            1.0                  1.0   
3                     3.0            3.0                  5.0   
4                     3.0            3.0                  2.0   

   is_seas_vacc_effective  is_seas_risky  sick_from_seas_vacc    age_bracket  \
0                     2.0            1.0                  2.0  55 - 64 Years   
1                     4.0            2.0                  4.0  35 - 44 Years   
2                     4.0            1.0                  2.0  18 - 34 Years   
3                     5.0            4.0                  1.0      65+ Years   
4                     3.0            1.0                  4.0  45 - 54 Years   

      qualification   race     sex               income_level marital_status  \
0        < 12 Years  White  Female              Below Poverty    Not Married   
1          12 Years  White    Male              Below Poverty    Not Married   
2  College Graduate  White    Male  <= $75,000, Above Poverty    Not Married   
3          12 Years  White  Female              Below Poverty    Not Married   
4      Some College  White  Female  <= $75,000, Above Poverty        Married   

  housing_status          employment                census_msa  no_of_adults  \
0            Own  Not in Labor Force                   Non-MSA           0.0   
1           Rent            Employed  MSA, Not Principle  City           0.0   
2            Own            Employed  MSA, Not Principle  City           2.0   
3           Rent  Not in Labor Force       MSA, Principle City           0.0   
4            Own            Employed  MSA, Not Principle  City           1.0   

   no_of_children  h1n1_vaccine  
0             0.0             0  
1             0.0             0  
2   

In [4]:
df.shape

(26707, 34)

In [5]:
df.isnull().sum().sum()

33962

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   unique_id                  26707 non-null  int64  
 1   h1n1_worry                 26615 non-null  float64
 2   h1n1_awareness             26591 non-null  float64
 3   antiviral_medication       26636 non-null  float64
 4   contact_avoidance          26499 non-null  float64
 5   bought_face_mask           26688 non-null  float64
 6   wash_hands_frequently      26665 non-null  float64
 7   avoid_large_gatherings     26620 non-null  float64
 8   reduced_outside_home_cont  26625 non-null  float64
 9   avoid_touch_face           26579 non-null  float64
 10  dr_recc_h1n1_vacc          24547 non-null  float64
 11  dr_recc_seasonal_vacc      24547 non-null  float64
 12  chronic_medic_condition    25736 non-null  float64
 13  cont_child_undr_6_mnths    25887 non-null  flo

In [7]:
len(df.unique_id)

26707

In [8]:
for i in df.columns:
    if df[i].isnull().sum()>10000:
        print(i)

has_health_insur


In [9]:
df['has_health_insur'].isnull().sum()

12274

In [10]:
df.drop(columns=['unique_id'], axis=1, inplace=True)

In [11]:
df.h1n1_vaccine.value_counts()

0    21033
1     5674
Name: h1n1_vaccine, dtype: int64

In [12]:
df.h1n1_vaccine.isnull().sum()

0

In [13]:
df.h1n1_worry.value_counts()

2.0    10575
1.0     8153
3.0     4591
0.0     3296
Name: h1n1_worry, dtype: int64

In [14]:
df.h1n1_worry.isnull().sum()

92

In [15]:
df.h1n1_worry.fillna(2.0,inplace = True) # filling the null values with mode

In [16]:
df.h1n1_worry.isnull().sum()

0

In [17]:
# h1n1_vaccine, h1n1_worry

In [18]:
df_tabel = pd.crosstab(df['h1n1_worry'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine     0     1
h1n1_worry              
0.0           2849   447
1.0           6756  1397
2.0           8178  2489
3.0           3250  1341


In [19]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[2849  447]
 [6756 1397]
 [8178 2489]
 [3250 1341]]


In [20]:
stats.chi2_contingency(observed_values)

(400.4620379252815,
 1.7582253892199257e-86,
 3,
 array([[2595.752724  ,  700.247276  ],
        [6420.86527877, 1732.13472123],
        [8400.75676789, 2266.24323211],
        [3615.62522934,  975.37477066]]))

In [21]:
df.h1n1_awareness.value_counts()

1.0    14598
2.0     9487
0.0     2506
Name: h1n1_awareness, dtype: int64

In [22]:
df.h1n1_awareness.isnull().sum()

116

In [23]:
df.h1n1_awareness.fillna(1.0,inplace=True) # filling the null values with mode

In [24]:
df.h1n1_awareness.isnull().sum()

0

In [25]:
df_tabel = pd.crosstab(df['h1n1_awareness'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine        0     1
h1n1_awareness             
0.0              2145   361
1.0             12039  2675
2.0              6849  2638


In [26]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 2145   361]
 [12039  2675]
 [ 6849  2638]]


In [27]:
stats.chi2_contingency(observed_values)

(396.7931990299987,
 6.877832615401085e-87,
 2,
 array([[ 1973.59111843,   532.40888157],
        [11587.95679035,  3126.04320965],
        [ 7471.45209121,  2015.54790879]]))

In [28]:
df.antiviral_medication.value_counts()

0.0    25335
1.0     1301
Name: antiviral_medication, dtype: int64

In [29]:
df.antiviral_medication.isnull().sum()

71

In [30]:
df.antiviral_medication.fillna(0.0,inplace=True)

In [31]:
df.antiviral_medication.isnull().sum()

0

In [32]:
df_tabel = pd.crosstab(df['antiviral_medication'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine              0     1
antiviral_medication             
0.0                   20103  5303
1.0                     930   371


In [33]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[20103  5303]
 [  930   371]]


In [34]:
stats.chi2_contingency(observed_values)

(42.75923842883827,
 6.190881602149606e-11,
 1,
 array([[20008.40221665,  5397.59778335],
        [ 1024.59778335,   276.40221665]]))

In [35]:
df.contact_avoidance.value_counts()

1.0    19228
0.0     7271
Name: contact_avoidance, dtype: int64

In [36]:
df.contact_avoidance.isnull().sum()

208

In [37]:
df.contact_avoidance.fillna(1.0,inplace = True)

In [38]:
df.contact_avoidance.isnull().sum()

0

In [39]:
df_tabel = pd.crosstab(df['contact_avoidance'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine           0     1
contact_avoidance             
0.0                 5954  1317
1.0                15079  4357


In [40]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 5954  1317]
 [15079  4357]]


In [41]:
stats.chi2_contingency(observed_values)

(58.330240730060524,
 2.2161129058289884e-14,
 1,
 array([[ 5726.24941027,  1544.75058973],
        [15306.75058973,  4129.24941027]]))

In [42]:
df.bought_face_mask.value_counts()

0.0    24847
1.0     1841
Name: bought_face_mask, dtype: int64

In [43]:
df.bought_face_mask.isnull().sum()

19

In [44]:
df.bought_face_mask.fillna(0.0,inplace = True)

In [45]:
df.bought_face_mask.isnull().sum()

0

In [46]:
df_tabel = pd.crosstab(df['bought_face_mask'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine          0     1
bought_face_mask             
0.0               19778  5088
1.0                1255   586


In [47]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[19778  5088]
 [ 1255   586]]


In [48]:
stats.chi2_contingency(observed_values)

(131.7334457101758,
 1.7112022110037095e-30,
 1,
 array([[19583.12719512,  5282.87280488],
        [ 1449.87280488,   391.12719512]]))

In [49]:
df.wash_hands_frequently.value_counts()

1.0    22015
0.0     4650
Name: wash_hands_frequently, dtype: int64

In [50]:
df.wash_hands_frequently.isnull().sum()

42

In [51]:
df.wash_hands_frequently.fillna(1.0,inplace= True)

In [52]:
df.wash_hands_frequently.isnull().sum()

0

In [53]:
df_tabel = pd.crosstab(df['wash_hands_frequently'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine               0     1
wash_hands_frequently             
0.0                     3971   679
1.0                    17062  4995


In [54]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 3971   679]
 [17062  4995]]


In [55]:
stats.chi2_contingency(observed_values)

(148.02701040329165,
 4.679794352605926e-34,
 1,
 array([[ 3662.09046317,   987.90953683],
        [17370.90953683,  4686.09046317]]))

In [56]:
df.avoid_large_gatherings.value_counts()

0.0    17073
1.0     9547
Name: avoid_large_gatherings, dtype: int64

In [57]:
df.avoid_large_gatherings.isnull().sum()

87

In [58]:
df.avoid_large_gatherings.fillna(0.0,inplace= True)

In [59]:
df.avoid_large_gatherings.isnull().sum()

0

In [60]:
df_tabel = pd.crosstab(df['avoid_large_gatherings'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine                0     1
avoid_large_gatherings             
0.0                     13609  3551
1.0                      7424  2123


In [61]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[13609  3551]
 [ 7424  2123]]


In [62]:
stats.chi2_contingency(observed_values)

(8.646638092006247,
 0.003276654049065037,
 1,
 array([[13514.29512862,  3645.70487138],
        [ 7518.70487138,  2028.29512862]]))

In [63]:
df.reduced_outside_home_cont.value_counts()

0.0    17644
1.0     8981
Name: reduced_outside_home_cont, dtype: int64

In [64]:
df.reduced_outside_home_cont.isnull().sum()

82

In [65]:
df.reduced_outside_home_cont.fillna(0.0,inplace= True)

In [66]:
df.reduced_outside_home_cont.isnull().sum()

0

In [67]:
df_tabel = pd.crosstab(df['reduced_outside_home_cont'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine                   0     1
reduced_outside_home_cont             
0.0                        14074  3652
1.0                         6959  2022


In [68]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[14074  3652]
 [ 6959  2022]]


In [69]:
stats.chi2_contingency(observed_values)

(12.905838675757487,
 0.00032755872863934096,
 1,
 array([[13960.04635489,  3765.95364511],
        [ 7072.95364511,  1908.04635489]]))

In [70]:
df.avoid_touch_face.value_counts()

1.0    18001
0.0     8578
Name: avoid_touch_face, dtype: int64

In [71]:
df.avoid_touch_face.isnull().sum()

128

In [72]:
df.avoid_touch_face.fillna(1.0,inplace= True)

In [73]:
df.avoid_touch_face.isnull().sum()

0

In [74]:
df_tabel = pd.crosstab(df['avoid_touch_face'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine          0     1
avoid_touch_face             
0.0                7117  1461
1.0               13916  4213


In [75]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 7117  1461]
 [13916  4213]]


In [76]:
stats.chi2_contingency(observed_values)

(133.71030825608494,
 6.3218424278463514e-31,
 1,
 array([[ 6755.57247164,  1822.42752836],
        [14277.42752836,  3851.57247164]]))

In [77]:
df.dr_recc_h1n1_vacc.value_counts()

0.0    19139
1.0     5408
Name: dr_recc_h1n1_vacc, dtype: int64

In [78]:
df.dr_recc_h1n1_vacc.isnull().sum()

2160

In [79]:
df.dr_recc_h1n1_vacc.fillna(0.0,inplace= True)

In [80]:
df.dr_recc_h1n1_vacc.isnull().sum()

0

In [81]:
df_tabel = pd.crosstab(df['dr_recc_h1n1_vacc'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine           0     1
dr_recc_h1n1_vacc             
0.0                18504  2795
1.0                 2529  2879


In [82]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[18504  2795]
 [ 2529  2879]]


In [83]:
stats.chi2_contingency(observed_values)

(4145.294661439282,
 0.0,
 1,
 array([[16773.94941401,  4525.05058599],
        [ 4259.05058599,  1148.94941401]]))

In [84]:
df.dr_recc_seasonal_vacc.value_counts()

0.0    16453
1.0     8094
Name: dr_recc_seasonal_vacc, dtype: int64

In [85]:
df.dr_recc_seasonal_vacc.isnull().sum()

2160

In [86]:
df.dr_recc_seasonal_vacc.fillna(0.0,inplace= True)

In [87]:
df.dr_recc_seasonal_vacc.isnull().sum()

0

In [88]:
df_tabel = pd.crosstab(df['dr_recc_seasonal_vacc'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine               0     1
dr_recc_seasonal_vacc             
0.0                    15758  2855
1.0                     5275  2819


In [89]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[15758  2855]
 [ 5275  2819]]


In [90]:
stats.chi2_contingency(observed_values)

(1279.444850950977,
 3.3126165190104603e-280,
 1,
 array([[14658.59995507,  3954.40004493],
        [ 6374.40004493,  1719.59995507]]))

In [91]:
df.chronic_medic_condition.value_counts()

0.0    18446
1.0     7290
Name: chronic_medic_condition, dtype: int64

In [92]:
df.chronic_medic_condition.isnull().sum()

971

In [93]:
df.chronic_medic_condition.fillna(0.0,inplace=True)

In [94]:
df.chronic_medic_condition.isnull().sum()

0

In [95]:
df_tabel = pd.crosstab(df['chronic_medic_condition'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine                 0     1
chronic_medic_condition             
0.0                      15751  3666
1.0                       5282  2008


In [96]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[15751  3666]
 [ 5282  2008]]


In [97]:
stats.chi2_contingency(observed_values)

(237.2776362003578,
 1.5428233060113362e-53,
 1,
 array([[15291.78720935,  4125.21279065],
        [ 5741.21279065,  1548.78720935]]))

In [98]:
df.cont_child_undr_6_mnths.value_counts()

0.0    23749
1.0     2138
Name: cont_child_undr_6_mnths, dtype: int64

In [99]:
df.cont_child_undr_6_mnths.isnull().sum()

820

In [100]:
df.cont_child_undr_6_mnths.fillna(0.0,inplace=True)

In [101]:
df.cont_child_undr_6_mnths.isnull().sum()

0

In [102]:
df_tabel = pd.crosstab(df['cont_child_undr_6_mnths'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine                 0     1
cont_child_undr_6_mnths             
0.0                      19547  5022
1.0                       1486   652


In [103]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[19547  5022]
 [ 1486   652]]


In [104]:
stats.chi2_contingency(observed_values)

(118.25774127744958,
 1.5225977070738918e-27,
 1,
 array([[19349.22593328,  5219.77406672],
        [ 1683.77406672,   454.22593328]]))

In [105]:
#is_health_worker

In [106]:
df.is_health_worker.value_counts()

0.0    23004
1.0     2899
Name: is_health_worker, dtype: int64

In [107]:
df.is_health_worker.isnull().sum()

804

In [108]:
df.is_health_worker.fillna(0.0,inplace=True)

In [109]:
df.is_health_worker.isnull().sum()

0

In [110]:
df_tabel = pd.crosstab(df['is_health_worker'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine          0     1
is_health_worker             
0.0               19321  4487
1.0                1712  1187


In [111]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[19321  4487]
 [ 1712  1187]]


In [112]:
stats.chi2_contingency(observed_values)

(752.9607596778831,
 9.112289333676525e-166,
 1,
 array([[18749.90317145,  5058.09682855],
        [ 2283.09682855,   615.90317145]]))

In [113]:
# has_health_insur

In [114]:
df.has_health_insur.value_counts()

1.0    12697
0.0     1736
Name: has_health_insur, dtype: int64

In [115]:
df.has_health_insur.isnull().sum()

12274

In [116]:
df.has_health_insur.fillna(1.0,inplace=True)

In [117]:
df.has_health_insur.isnull().sum()

0

In [118]:
df_tabel = pd.crosstab(df['has_health_insur'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine          0     1
has_health_insur             
0.0                1480   256
1.0               19553  5418


In [119]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 1480   256]
 [19553  5418]]


In [120]:
stats.chi2_contingency(observed_values)

(46.45258649399282,
 9.386237644434308e-12,
 1,
 array([[ 1367.18043959,   368.81956041],
        [19665.81956041,  5305.18043959]]))

In [121]:
# is_h1n1_vacc_effective

In [122]:
df.is_h1n1_vacc_effective.value_counts()

4.0    11683
5.0     7166
3.0     4723
2.0     1858
1.0      886
Name: is_h1n1_vacc_effective, dtype: int64

In [123]:
df.is_h1n1_vacc_effective.isnull().sum()

391

In [124]:
df.is_h1n1_vacc_effective.fillna(4.0,inplace=True)

In [125]:
df.is_h1n1_vacc_effective.isnull().sum()

0

In [126]:
df_tabel = pd.crosstab(df['is_h1n1_vacc_effective'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine               0     1
is_h1n1_vacc_effective            
1.0                      844    42
2.0                     1763    95
3.0                     4224   499
4.0                     9937  2137
5.0                     4265  2901


In [127]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[ 844   42]
 [1763   95]
 [4224  499]
 [9937 2137]
 [4265 2901]]


In [128]:
stats.chi2_contingency(observed_values)

(2430.9882283574093,
 0.0,
 4,
 array([[ 697.76605384,  188.23394616],
        [1463.2610926 ,  394.7389074 ],
        [3719.58134571, 1003.41865429],
        [9508.83446287, 2565.16553713],
        [5643.55704497, 1522.44295503]]))

In [129]:
# is_h1n1_risky

In [130]:
df.is_h1n1_risky.value_counts()

2.0    9919
1.0    8139
4.0    5394
5.0    1750
3.0    1117
Name: is_h1n1_risky, dtype: int64

In [131]:
df.is_h1n1_risky.isnull().sum()

388

In [132]:
df.is_h1n1_risky.fillna(2.0,inplace=True)

In [133]:
df.is_h1n1_risky.isnull().sum()

0

In [134]:
df_tabel = pd.crosstab(df['is_h1n1_risky'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine      0     1
is_h1n1_risky            
1.0            7420   719
2.0            8555  1752
3.0             923   194
4.0            3279  2115
5.0             856   894


In [135]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[7420  719]
 [8555 1752]
 [ 923  194]
 [3279 2115]
 [ 856  894]]


In [136]:
stats.chi2_contingency(observed_values)

(2842.259854334096,
 0.0,
 4,
 array([[6409.83963006, 1729.16036994],
        [8117.24008687, 2189.75991313],
        [ 879.6892575 ,  237.3107425 ],
        [4248.02493728, 1145.97506272],
        [1378.20608829,  371.79391171]]))

In [137]:
# sick_from_h1n1_vacc

In [138]:
df.sick_from_h1n1_vacc.value_counts()

2.0    9129
1.0    8998
4.0    5850
5.0    2187
3.0     148
Name: sick_from_h1n1_vacc, dtype: int64

In [139]:
df.sick_from_h1n1_vacc.isnull().sum()

395

In [140]:
df.sick_from_h1n1_vacc.fillna(2.0,inplace=True)

In [141]:
df.sick_from_h1n1_vacc.isnull().sum()

0

In [142]:
df_tabel = pd.crosstab(df['sick_from_h1n1_vacc'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine            0     1
sick_from_h1n1_vacc            
1.0                  7157  1841
2.0                  7862  1662
3.0                   136    12
4.0                  4304  1546
5.0                  1574   613


In [143]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[7157 1841]
 [7862 1662]
 [ 136   12]
 [4304 1546]
 [1574  613]]


In [144]:
stats.chi2_contingency(observed_values)

(254.59089268297026,
 6.675769368968441e-54,
 4,
 array([[7086.34193283, 1911.65806717],
        [7500.59130565, 2023.40869435],
        [ 116.55685775,   31.44314225],
        [4607.14606657, 1242.85393343],
        [1722.3638372 ,  464.6361628 ]]))

In [145]:
# is_seas_vacc_effective

In [146]:
df.is_seas_vacc_effective.value_counts()

4.0    11629
5.0     9973
2.0     2206
1.0     1221
3.0     1216
Name: is_seas_vacc_effective, dtype: int64

In [147]:
df.is_seas_vacc_effective.isnull().sum()

462

In [148]:
df.is_seas_vacc_effective.fillna(4.0,inplace=True)

In [149]:
df.is_seas_vacc_effective.isnull().sum()

0

In [150]:
df_tabel = pd.crosstab(df['is_seas_vacc_effective'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine               0     1
is_seas_vacc_effective            
1.0                     1132    89
2.0                     2001   205
3.0                     1054   162
4.0                     9949  2142
5.0                     6897  3076


In [151]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[1132   89]
 [2001  205]
 [1054  162]
 [9949 2142]
 [6897 3076]]


In [152]:
stats.chi2_contingency(observed_values)

(1015.2358583203843,
 1.7812550798256757e-218,
 4,
 array([[ 961.59407646,  259.40592354],
        [1737.32721758,  468.67278242],
        [ 957.65634478,  258.34365522],
        [9522.22275059, 2568.77724941],
        [7854.19961059, 2118.80038941]]))

In [153]:
df.is_seas_risky.value_counts()

2.0    8954
4.0    7630
1.0    5974
5.0    2958
3.0     677
Name: is_seas_risky, dtype: int64

In [154]:
df.is_seas_risky.isnull().sum()

514

In [155]:
df.is_seas_risky.fillna(2.0,inplace = True)

In [156]:
df.is_seas_risky.isnull().sum()

0

In [157]:
df_tabel = pd.crosstab(df['is_seas_risky'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine      0     1
is_seas_risky            
1.0            5468   506
2.0            7953  1515
3.0             541   136
4.0            5295  2335
5.0            1776  1182


In [158]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[5468  506]
 [7953 1515]
 [ 541  136]
 [5295 2335]
 [1776 1182]]


In [159]:
stats.chi2_contingency(observed_values)

(1757.3448032431027,
 0.0,
 4,
 array([[4704.80181226, 1269.19818774],
        [7456.48871082, 2011.51128918],
        [ 533.16886958,  143.83113042],
        [6008.97854495, 1621.02145505],
        [2329.56206238,  628.43793762]]))

In [160]:
df.sick_from_seas_vacc.value_counts()

1.0    11870
2.0     7633
4.0     4852
5.0     1721
3.0       94
Name: sick_from_seas_vacc, dtype: int64

In [161]:
df.sick_from_seas_vacc.isnull().sum()

537

In [162]:
df.sick_from_seas_vacc.fillna(1.0,inplace= True)

In [163]:
df.sick_from_seas_vacc.isnull().sum()

0

In [164]:
df_tabel = pd.crosstab(df['sick_from_seas_vacc'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine            0     1
sick_from_seas_vacc            
1.0                  9691  2716
2.0                  6183  1450
3.0                    86     8
4.0                  3740  1112
5.0                  1333   388


In [165]:
#observed values
observed_values = df_tabel.values
print('Observed values:-\n',observed_values)

Observed values:-
 [[9691 2716]
 [6183 1450]
 [  86    8]
 [3740 1112]
 [1333  388]]


In [166]:
stats.chi2_contingency(observed_values)

(45.127510978784706,
 3.7405030013106724e-09,
 4,
 array([[9771.08739282, 2635.91260718],
        [6011.34118396, 1621.65881604],
        [  74.0293556 ,   19.9706444 ],
        [3821.17482308, 1030.82517692],
        [1355.36724454,  365.63275546]]))

In [167]:
df.age_bracket.value_counts()

65+ Years        6843
55 - 64 Years    5563
45 - 54 Years    5238
18 - 34 Years    5215
35 - 44 Years    3848
Name: age_bracket, dtype: int64

In [168]:
df.age_bracket.isnull().sum()

0

In [169]:
df_tabel = pd.crosstab(df['age_bracket'],df['h1n1_vaccine'])
print(df_tabel)

h1n1_vaccine      0     1
age_bracket              
18 - 34 Years  4224   991
35 - 44 Years  3087   761
45 - 54 Years  4218  1020
55 - 64 Years  4212  1351
65+ Years      5292  1551


In [170]:
observation_values = df_tabel.values
print(observation_values)

[[4224  991]
 [3087  761]
 [4218 1020]
 [4212 1351]
 [5292 1551]]


In [171]:
stats.chi2_contingency(observation_values)

(69.44576247937547,
 2.9716028185463074e-14,
 4,
 array([[4107.05414311, 1107.94585689],
        [3030.47830157,  817.52169843],
        [4125.16770884, 1112.83229116],
        [4381.12026809, 1181.87973191],
        [5389.17957839, 1453.82042161]]))

In [173]:
df.qualification.value_counts()

College Graduate    10097
Some College         7043
12 Years             5797
< 12 Years           2363
Name: qualification, dtype: int64

In [174]:
df.qualification.isnull().sum()

1407

In [175]:
df.qualification.fillna('College Graduate',inplace=True)

In [176]:
df.qualification.isnull().sum()

0

In [177]:
df_tabel = pd.crosstab(df.qualification,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine         0     1
qualification               
12 Years          4726  1071
< 12 Years        1968   395
College Graduate  8760  2744
Some College      5579  1464


In [178]:
observation_values = df_tabel.values
print(observation_values)

[[4726 1071]
 [1968  395]
 [8760 2744]
 [5579 1464]]


In [180]:
stats.chi2_contingency(observation_values)

(103.18537711307252,
 3.209804092590849e-22,
 3,
 array([[4565.40611076, 1231.59388924],
        [1860.97199236,  502.02800764],
        [9059.93305126, 2444.06694874],
        [5546.68884562, 1496.31115438]]))

In [184]:
df.race.value_counts()

White                21222
Black                 2118
Hispanic              1755
Other or Multiple     1612
Name: race, dtype: int64

In [185]:
df.race.isnull().sum()

0

In [187]:
df_tabel = pd.crosstab(df.race,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine           0     1
race                          
Black               1803   315
Hispanic            1390   365
Other or Multiple   1263   349
White              16577  4645


In [188]:
observed_values = df_tabel.values
observed_values

array([[ 1803,   315],
       [ 1390,   365],
       [ 1263,   349],
       [16577,  4645]], dtype=int64)

In [191]:
stats.chi2_contingency(observed_values)

(57.01119582422927,
 2.5557770361705444e-12,
 3,
 array([[ 1668.02314   ,   449.97686   ],
        [ 1382.14381997,   372.85618003],
        [ 1269.5246939 ,   342.4753061 ],
        [16713.30834613,  4508.69165387]]))

In [192]:
df.sex.value_counts()

Female    15858
Male      10849
Name: sex, dtype: int64

In [194]:
df.sex.isnull().sum()

0

In [195]:
df_tabel = pd.crosstab(df.sex,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine      0     1
sex                      
Female        12378  3480
Male           8655  2194


In [196]:
observed_values = df_tabel.values
print(observed_values)

[[12378  3480]
 [ 8655  2194]]


In [197]:
stats.chi2_contingency(observed_values)

(11.309981152455997,
 0.0007709155489949327,
 1,
 array([[12488.90979893,  3369.09020107],
        [ 8544.09020107,  2304.90979893]]))

In [200]:
df.income_level.value_counts()

<= $75,000, Above Poverty    12777
> $75,000                     6810
Below Poverty                 2697
Name: income_level, dtype: int64

In [201]:
df.income_level.isnull().sum()

4423

In [202]:
df.income_level.fillna('<= $75,000, Above Poverty',inplace=True)

In [203]:
df.income_level.isnull().sum()

0

In [204]:
df_tabel = pd.crosstab(df.income_level,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine                   0     1
income_level                          
<= $75,000, Above Poverty  13765  3435
> $75,000                   5087  1723
Below Poverty               2181   516


In [205]:
observed_values = df_tabel.values
print(observed_values)

[[13765  3435]
 [ 5087  1723]
 [ 2181   516]]


In [207]:
stats.chi2_contingency(observed_values)

(90.84009217768136,
 1.880722047715149e-20,
 2,
 array([[13545.79698206,  3654.20301794],
        [ 5363.19054929,  1446.80945071],
        [ 2124.01246864,   572.98753136]]))

In [208]:
df.fillna(method='ffill',inplace=True)

In [211]:
df.isnull().sum()

h1n1_worry                   0
h1n1_awareness               0
antiviral_medication         0
contact_avoidance            0
bought_face_mask             0
wash_hands_frequently        0
avoid_large_gatherings       0
reduced_outside_home_cont    0
avoid_touch_face             0
dr_recc_h1n1_vacc            0
dr_recc_seasonal_vacc        0
chronic_medic_condition      0
cont_child_undr_6_mnths      0
is_health_worker             0
has_health_insur             0
is_h1n1_vacc_effective       0
is_h1n1_risky                0
sick_from_h1n1_vacc          0
is_seas_vacc_effective       0
is_seas_risky                0
sick_from_seas_vacc          0
age_bracket                  0
qualification                0
race                         0
sex                          0
income_level                 0
marital_status               0
housing_status               0
employment                   0
census_msa                   0
no_of_adults                 0
no_of_children               0
h1n1_vac

In [212]:
df.marital_status.value_counts()

Married        14312
Not Married    12395
Name: marital_status, dtype: int64

In [214]:
df_tabel = pd.crosstab(df.marital_status,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine        0     1
marital_status             
Married         11011  3301
Not Married     10022  2373


In [215]:
observed_values = df_tabel.values
print(observed_values)

[[11011  3301]
 [10022  2373]]


In [226]:
stats.chi2_contingency(observed_values,4)

(60.7613407816723,
 6.443086899351007e-15,
 1,
 array([[11271.36316322,  3040.63683678],
        [ 9761.63683678,  2633.36316322]]))

In [227]:
df.housing_status.value_counts()

Own     20284
Rent     6423
Name: housing_status, dtype: int64

In [218]:
# Chi-square test of independence. 
c, p, dof, expected = chi2_contingency(contigency) 
# Print the p-value
print(p)

NameError: name 'chi2_contingency' is not defined

In [229]:
df_tabel = pd.crosstab(df.housing_status,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine        0     1
housing_status             
Own             15836  4448
Rent             5197  1226


In [230]:
observed_values = df_tabel.values
print(observed_values)

[[15836  4448]
 [ 5197  1226]]


In [231]:
stats.chi2_contingency(observed_values)

(23.362373569970778,
 1.3417759909486258e-06,
 1,
 array([[15974.5898828,  4309.4101172],
        [ 5058.4101172,  1364.5898828]]))

In [232]:
df.employment.value_counts()

Employed              14360
Not in Labor Force    10808
Unemployed             1539
Name: employment, dtype: int64

In [233]:
df_tabel = pd.crosstab(df.employment,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine            0     1
employment                     
Employed            11298  3062
Not in Labor Force   8450  2358
Unemployed           1285   254


In [234]:
observed_values = df_tabel.values
print(observed_values)

[[11298  3062]
 [ 8450  2358]
 [ 1285   254]]


In [235]:
stats.chi2_contingency(observed_values)

(22.83982538393645,
 1.0974757532385518e-05,
 2,
 array([[11309.16538735,  3050.83461265],
        [ 8511.80080129,  2296.19919871],
        [ 1212.03381136,   326.96618864]]))

In [236]:
df.census_msa.value_counts()

MSA, Not Principle  City    11645
MSA, Principle City          7864
Non-MSA                      7198
Name: census_msa, dtype: int64

In [237]:
df_tabel = pd.crosstab(df.census_msa,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine                 0     1
census_msa                          
MSA, Not Principle  City  9178  2467
MSA, Principle City       6183  1681
Non-MSA                   5672  1526


In [238]:
observed_values = df_tabel.values
print(observed_values)

[[9178 2467]
 [6183 1681]
 [5672 1526]]


In [239]:
stats.chi2_contingency(observed_values)

(0.11411029118541836,
 0.9445419806029446,
 2,
 array([[9170.97708466, 2474.02291534],
        [6193.26438761, 1670.73561239],
        [5668.75852773, 1529.24147227]]))

In [240]:
df.no_of_adults.value_counts()

1.0    14621
0.0     8124
2.0     2824
3.0     1138
Name: no_of_adults, dtype: int64

In [241]:
df_tabel = pd.crosstab(df.no_of_adults,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine      0     1
no_of_adults             
0.0            6533  1591
1.0           11328  3293
2.0            2257   567
3.0             915   223


In [242]:
observed_values = df_tabel.values
print(observed_values)

[[ 6533  1591]
 [11328  3293]
 [ 2257   567]
 [  915   223]]


In [243]:
stats.chi2_contingency(observed_values)

(31.804597701690277,
 5.753961096124437e-07,
 3,
 array([[ 6398.02643502,  1725.97356498],
        [11514.71498109,  3106.28501891],
        [ 2224.03085333,   599.96914667],
        [  896.22773056,   241.77226944]]))

In [ ]:
             25299 non-null  object 
 27               24665 non-null  object 
 28                   25244 non-null  object 
 29                   26707 non-null  object 
 30                 26458 non-null  float64
 31               26458 non-null  float64
 32  h1n1_vaccine

In [244]:
df.no_of_children.value_counts()

0.0    18841
1.0     3208
2.0     2896
3.0     1762
Name: no_of_children, dtype: int64

In [245]:
df_tabel = pd.crosstab(df.no_of_children,df.h1n1_vaccine)
print(df_tabel)

h1n1_vaccine        0     1
no_of_children             
0.0             14833  4008
1.0              2528   680
2.0              2260   636
3.0              1412   350


In [246]:
observed_values = df_tabel.values
print(observed_values)

[[14833  4008]
 [ 2528   680]
 [ 2260   636]
 [ 1412   350]]


In [248]:
stats.chi2_contingency(observed_values)

(2.910245595178825,
 0.40567155730623383,
 3,
 array([[14838.16051971,  4002.83948029],
        [ 2526.44864642,   681.55135358],
        [ 2280.73418954,   615.26581046],
        [ 1387.65664433,   374.34335567]]))

In [249]:
df.sex.value_counts()

Female    15858
Male      10849
Name: sex, dtype: int64

In [251]:
df1 = pd.get_dummies(df['sex'],drop_first=True)

In [253]:
df = pd.concat([df1,df],axis=1)

In [255]:
df.drop('sex',axis=1,inplace=True)

In [259]:
df.race.value_counts()

White                21222
Black                 2118
Hispanic              1755
Other or Multiple     1612
Name: race, dtype: int64

In [261]:
df1 = pd.get_dummies(df['race'],drop_first=True)

In [263]:
df = pd.concat([df1,df],axis=1)

In [264]:
df.drop('race',axis=1,inplace=True)

In [266]:
df.marital_status.value_counts()

Married        14312
Not Married    12395
Name: marital_status, dtype: int64

In [268]:
df1 = pd.get_dummies(df['marital_status'],drop_first=True)

In [270]:
df = pd.concat([df1,df],axis=1)

In [272]:
df.drop('marital_status',axis=1,inplace=True)

In [274]:
df.housing_status.value_counts()

Own     20284
Rent     6423
Name: housing_status, dtype: int64

In [276]:
df1 = pd.get_dummies(df['housing_status'],drop_first=True)

In [278]:
df = pd.concat([df1,df],axis=1)

In [279]:
df.drop('housing_status',axis=1,inplace=True)

In [281]:
df.age_bracket.value_counts()

65+ Years        6843
55 - 64 Years    5563
45 - 54 Years    5238
18 - 34 Years    5215
35 - 44 Years    3848
Name: age_bracket, dtype: int64

In [283]:
df1 = pd.get_dummies(df['age_bracket'],drop_first=True)

In [285]:
df = pd.concat([df1,df],axis=1)

In [286]:
df.drop('age_bracket',axis=1,inplace=True)

In [288]:
df.qualification.value_counts()

College Graduate    11504
Some College         7043
12 Years             5797
< 12 Years           2363
Name: qualification, dtype: int64

In [290]:
df1 = pd.get_dummies(df['qualification'],drop_first=True)

In [292]:
df = pd.concat([df1,df],axis=1)

In [293]:
df.drop('qualification',axis=1,inplace=True)

In [295]:
df.income_level.value_counts()

<= $75,000, Above Poverty    17200
> $75,000                     6810
Below Poverty                 2697
Name: income_level, dtype: int64

In [297]:
df1 = pd.get_dummies(df['income_level'],drop_first=True)

In [299]:
df = pd.concat([df1,df],axis=1)

In [300]:
df.drop('income_level',axis=1,inplace=True)

In [302]:
df.employment.value_counts()

Employed              14360
Not in Labor Force    10808
Unemployed             1539
Name: employment, dtype: int64

In [304]:
df1 = pd.get_dummies(df['employment'],drop_first=True)

In [306]:
df = pd.concat([df1,df],axis=1)

In [307]:
df.drop('employment',axis=1,inplace=True)

In [309]:
df.drop(columns=['census_msa','no_of_children'],axis=1,inplace=True)

In [311]:
df.shape

(26707, 40)